#!/usr/bin/env python3
"""Generate a PNG graph using matplotlib.

Input:
- tools/out/rtos_wcet_vs_isr.csv (generated by tools/rtos_sweep_plot.py)

Output:
- tools/out/rtos_wcet_vs_isr.png

This keeps the simulator + sweep logic separate, and only focuses on
"render as an image" using matplotlib.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import subprocess
import sys

import matplotlib
import matplotlib.pyplot as plt


def load_csv(path: Path):
    rows = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            # Empty strings represent None
            def to_int_or_none(v: str):
                v = (v or "").strip()
                return None if v == "" else int(v)

            rows.append(
                {
                    "isr_tax_us": int(r["isr_tax_us"]),
                    "isr_percent": float(r["isr_percent"]),
                    "max_rt_only_ok_us": to_int_or_none(r["max_rt_only_ok_us"]),
                    "max_all_ok_us": to_int_or_none(r["max_all_ok_us"]),
                }
            )
    rows.sort(key=lambda x: x["isr_percent"])
    return rows


def main() -> int:
    p = argparse.ArgumentParser(
        description="Plot RTOS sweep CSV to PNG using matplotlib",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--csv",
        type=str,
        default=str(Path(__file__).resolve().parent / "out" / "rtos_wcet_vs_isr.csv"),
        help="Input CSV produced by tools/rtos_sweep_plot.py",
    )
    p.add_argument(
        "--out",
        type=str,
        default=str(Path(__file__).resolve().parent / "out" / "rtos_wcet_vs_isr.png"),
        help="Output PNG path",
    )
    p.add_argument("--dpi", type=int, default=160)
    p.add_argument("--title", type=str, default="Max safe RealTime WCET vs ISR load")

    p.add_argument(
        "--run-sweep",
        action="store_true",
        help="Run tools/rtos_sweep_plot.py first to generate/update the CSV, then render PNG",
    )
    p.add_argument("--sim-ms", type=int, default=5000, help="(sweep) Simulation time for CSV generation")
    p.add_argument("--quantum-us", type=int, default=100, help="(sweep) Quantum for CSV generation")
    p.add_argument(
        "--isr-tax-us-list",
        type=str,
        default="0,50,100,150,200",
        help="(sweep) Comma-separated ISR tax list, passed to tools/rtos_sweep_plot.py",
    )
    p.add_argument("--sweep-start-us", type=int, default=8000, help="(sweep) RT WCET sweep start")
    p.add_argument("--sweep-end-us", type=int, default=20000, help="(sweep) RT WCET sweep end")
    p.add_argument("--sweep-step-us", type=int, default=1000, help="(sweep) RT WCET sweep step")

    args = p.parse_args()

    csv_path = Path(args.csv)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.run_sweep or (not csv_path.exists()):
        sweep_script = Path(__file__).resolve().parent / "rtos_sweep_plot.py"
        cmd = [
            sys.executable,
            str(sweep_script),
            "--sim-ms",
            str(args.sim_ms),
            "--quantum-us",
            str(args.quantum_us),
            "--isr-tax-us-list",
            str(args.isr_tax_us_list),
            "--sweep-start-us",
            str(args.sweep_start_us),
            "--sweep-end-us",
            str(args.sweep_end_us),
            "--sweep-step-us",
            str(args.sweep_step_us),
            "--out-dir",
            str(out_path.parent),
        ]
        subprocess.run(cmd, check=True)

    rows = load_csv(csv_path)
    if not rows:
        raise SystemExit(f"No data rows in {csv_path}")

    x = [r["isr_percent"] for r in rows]

    def series(key: str):
        xs, ys = [], []
        for r in rows:
            v = r[key]
            if v is None:
                continue
            xs.append(r["isr_percent"])
            ys.append(v / 1000.0)  # us -> ms
        return xs, ys

    x_all, y_all = series("max_all_ok_us")
    x_rt, y_rt = series("max_rt_only_ok_us")

    # Headless-safe: use Agg backend if not already
    try:
        matplotlib.get_backend()
    except Exception:
        matplotlib.use("Agg")

    fig, ax = plt.subplots(figsize=(9.5, 5.2))

    if x_all:
        ax.plot(x_all, y_all, marker="o", linewidth=2.5, label="All tasks misses=0")
    if x_rt:
        ax.plot(x_rt, y_rt, marker="o", linewidth=2.5, label="RealTime only misses=0")

    ax.set_title(args.title)
    ax.set_xlabel("ISR load (approx, % CPU)")
    ax.set_ylabel("Max safe RealTime WCET (ms)")

    ax.grid(True, which="both", linestyle="--", linewidth=0.7, alpha=0.5)
    ax.legend(loc="best")

    # Nice x ticks: show all if small
    if len(x) <= 12:
        ax.set_xticks(x)

    fig.tight_layout()
    fig.savefig(out_path, dpi=args.dpi)

    print("Wrote:")
    print(f"- {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
