set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# ARM GCC 툴체인 경로 설정 (프로젝트 tools 폴더 사용)
set(ARM_TOOLCHAIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../tools/10 2021.10/bin")
set(TOOLCHAIN_PREFIX ${ARM_TOOLCHAIN_DIR}/arm-none-eabi-)

set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}gcc.exe" CACHE FILEPATH "C Compiler")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}g++.exe" CACHE FILEPATH "C++ Compiler")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}gcc.exe" CACHE FILEPATH "ASM Compiler")
set(CMAKE_OBJCOPY "${TOOLCHAIN_PREFIX}objcopy.exe" CACHE FILEPATH "objcopy")
set(CMAKE_SIZE "${TOOLCHAIN_PREFIX}size.exe" CACHE FILEPATH "size")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXECUTABLE_SUFFIX_C   ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")
